car.park:
  barrier.event.topic: car-park-barrier-events
  availability.output.topic: car-park-status
  store: hackton.car.park.space.store
  zone:
    capacity:
      SHIFT: 30
      RESERVED: 10
      GENERAL: 20
      MAIN: 60
kafka:
  stream:
    config:
      streamConfig:
        bootstrap.servers: localhost:9092
        application.id: sky.hackton.kstream.car.park.space.analyzer
        auto.offset.reset: earliest
        producer.compression.type: gzip
jackson:
  serialization.write_dates_as_timestamps: true