car.park:
  barrier.event.topic: car-park-barrier-events
  availability.output.topic: car-park-barrier-events
  store: hackton.car.park.space.store
  zone:
    zone-1:
      capacity: 10
      type: Shift
    zone-2:
      capacity: 30
      type: Reserved
kafka:
  stream:
    config:
      streamConfig:
        bootstrap.servers: localhost:9092
        application.id: sky.hackton.kstream.car.park.space.analyzer
        auto.offset.reset: earliest
        producer.compression.type: gzip
